version: 2.1

jobs:
  luatest:
    docker:
      - image: locimation/erlanglua_test
    steps:
      - checkout
      - run:
          name: "Run busted"
          command: "busted"

workflows:
  luatest-workflow:
    jobs:
      - luatest
