version: 2.1

jobs:
  luatest:
    docker:
      - image: mileschou/lua:5.3
    steps:
      - checkout
      - run:
          name: "Get wget"
          command: "apt-get update -y && apt-get install -y --no-install-recommends --no-install-suggests wget" 
      - run:
          name: "Install busted"
          command: "docker-luarocks-install busted"
      - run:
          name: "Run busted"
          command: "busted"

workflows:
  luatest-workflow:
    jobs:
      - luatest
