version: 2.1

jobs:
  luatest:
    docker:
      - image: mileschou/lua:5.3
    steps:
      - checkout
      - run:
          name: "Check for wget"
          command: "which wget" 
      - run:
          name: "Install busted"
          command: "docker-luarocks-install busted"
      - run:
          name: "Run busted"
          command: "busted"

workflows:
  luatest-workflow:
    jobs:
      - luatest
